workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.blackfabricsecurity.crossplatformblackfabric"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_ID: 1234567890

      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Fetch signing files (with Push Notifications)
        script: |
          echo "🔑 Fetching signing files with Push Notifications capability..."
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates
        script: |
          keychain add-certificates

      - name: Configure Push Notifications in Xcode Project
        script: |
          cd ios
          
          echo "📦 Installing xcodeproj Ruby gem..."
          gem install xcodeproj
          
          echo "🔧 Creating script to configure Push Notifications..."
          cat > configure_push.rb << 'RUBY_SCRIPT'
          require 'xcodeproj'
          
          project_path = 'Runner.xcodeproj'
          project = Xcodeproj::Project.open(project_path)
          
          # Get the Runner target
          target = project.targets.first
          puts "🎯 Configuring target: #{target.name}"
          
          # Set entitlements file for ALL configurations
          target.build_configurations.each do |config|
            puts "⚙️  Setting entitlements for #{config.name} configuration"
            config.build_settings['CODE_SIGN_ENTITLEMENTS'] = 'Runner/Runner.entitlements'
          
            # Ensure proper iOS deployment target
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          
            # Enable push notifications
            config.build_settings['ENABLE_BITCODE'] = 'NO'
          end
          
          # Save the project
          project.save
          puts "✅ Xcode project configured successfully"
          RUBY_SCRIPT
          
          echo "🚀 Running configuration script..."
          ruby configure_push.rb
          
          echo "📋 Verifying entitlements file exists..."
          if [ ! -f "Runner/Runner.entitlements" ]; then
            echo "❌ ERROR: Entitlements file not found!"
            echo "Creating it now..."
          
            cat > Runner/Runner.entitlements << 'ENTITLEMENTS'
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  <key>aps-environment</key>
  <string>development</string>
  </dict>
  </plist>
  ENTITLEMENTS
  echo "✅ Entitlements file created"
  fi
  
  echo "📄 Entitlements file contents:"
  cat Runner/Runner.entitlements
  
  echo "🔍 Verifying Xcode project settings..."
grep -A 2 "CODE_SIGN_ENTITLEMENTS" Runner.xcodeproj/project.pbxproj || echo "⚠️  Warning: Entitlements not found in project"
  
  cd ..

- name: Set up code signing
  script: |
    xcode-project use-profiles

- name: Get Flutter packages
  script: |
    flutter packages pub get

- name: Clean build artifacts
  script: |
    flutter clean
    cd ios
    rm -rf Pods
    rm -rf Podfile.lock
    rm -rf .symlinks
    rm -rf Flutter/Flutter.framework
    rm -rf Flutter/Flutter.podspec
    cd ..

- name: Install CocoaPods
  script: |
    cd ios
    pod cache clean --all
    pod deintegrate || true
    pod install --repo-update
    cd ..

- name: Verify Configuration Before Build
  script: |
    echo "🔍 Final verification before build..."
    
    echo "1️⃣ Checking entitlements file:"
    cat ios/Runner/Runner.entitlements
    
    echo ""
    echo "2️⃣ Checking Xcode project for entitlements:"
    grep "CODE_SIGN_ENTITLEMENTS" ios/Runner.xcodeproj/project.pbxproj | head -5
    
    echo ""
    echo "3️⃣ Checking GoogleService-Info.plist:"
    if [ -f "ios/Runner/GoogleService-Info.plist" ]; then
      echo "✅ GoogleService-Info.plist exists"
    else
      echo "❌ GoogleService-Info.plist MISSING!"
    fi
    
    echo ""
    echo "4️⃣ Checking AppDelegate.swift:"
    if grep -q "UNUserNotificationCenter" ios/Runner/AppDelegate.swift; then
      echo "✅ AppDelegate has notification setup"
    else
      echo "❌ AppDelegate missing notification setup!"
    fi

- name: Build iOS app
  script: |
    echo "🏗️  Building iOS app..."
    flutter build ipa --release \
      --export-options-plist=/Users/builder/export_options.plist
    
    echo "✅ Build completed!"

artifacts:
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - flutter_drive.log

publishing:
  email:
    recipients:
      - your-email@example.com
    notify:
      success: true
      failure: true

  app_store_connect:
    submit_to_testflight: true